"""
Dutch name generation module for demo elections.

Generates candidate names by pairing Dutch first names with real Dutch
surnames drawn from a curated pool, avoiding any surnames already present
in the member database.  Falls back to a fixed list when no member data
is available.
"""

import csv
import os
import random
import re
import sqlite3

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

FIRST_NAMES = [
    "Peter", "Henry", "William", "Gary", "James", "Neil",
    "Seb", "Adrian", "Andrew", "Derek", "Ryan", "Fred",
    "John", "Martin", "Scott", "Ted", "Chris", "Roger",
    "Albert", "Tony", "Mark", "Eric", "Isaac", "Nick",
    "Tom", "Rob", "Quintin",
]

DUTCH_PARTICLES = ["van", "de", "van der", "ten", "ter", "van den"]

FALLBACK_ELDER_CANDIDATES = [
    "Henry Brouwerhof",
    "James Groenevelt",
    "William de Kempenaar",
    "Neil ten Heuvel",
    "Gary van Dijkstra",
    "Peter van Rijksen",
]

FALLBACK_DEACON_CANDIDATES = [
    "Fred Bosveldt",
    "Ryan Mulderhoek",
    "Derek van Leeuwenburg",
    "Andrew Visserman",
]

# Real Dutch surnames — common and recognisable.  The pool is large enough
# that even after excluding members already in the database we can still
# pick 8+ unique candidates.
DUTCH_SURNAMES = [
    "Bakker", "Bos", "Bosman", "Bouwman", "Brouwer", "Derksen",
    "Dekker", "Dijkstra", "Evers", "Groen", "Groenendijk",
    "Hendriks", "Hoekstra", "Hofman", "Janssen", "Jonker",
    "Kamphuis", "Kievit", "Klaasen", "Kloosterman",
    "Koning", "Kramer", "Kuipers", "Lammers",
    "Molenaar", "Mulder", "Nauta", "Nieuwenhuis",
    "Oosterbeek", "Ottens", "Peeters", "Plantinga",
    "Postma", "Prins", "Rietveld", "Roelofs", "Schouten",
    "Schipper", "Smit", "Steenstra", "Timmerman", "Tuinstra",
    "van Beek", "van den Berg", "van der Heijden",
    "van der Meer", "van der Wal", "van Dijk", "van Leeuwen",
    "Veenstra", "Veldman", "Vermeer", "Visser", "Vlietstra",
    "Vos", "de Vries", "de Wit", "Wielinga", "Wieringa",
    "Wolters", "Zijlstra",
]

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_PARTICLE_PATTERN = re.compile(
    r"^(?:van der|van den|van de|van|de|ten|ter)\s+",
    re.IGNORECASE,
)

def _extract_surname(full_name):
    """Extract the surname from a full name (everything after the first token).

    Returns the full surname string (including any particle) or None.
    """
    if not full_name:
        return None
    parts = full_name.strip().split()
    if len(parts) < 2:
        return None
    # Everything after the first name token is the surname
    return " ".join(parts[1:])


def _generate_names_from_pool(member_names, count=8):
    """Generate candidate names using real Dutch surnames from a curated pool.

    Surnames already present in the member list are excluded so that demo
    candidates are clearly distinct from real members.  Each selected surname
    is paired with a random Dutch first name.

    Returns a list of unique generated name strings of length `count`.
    """
    # Collect member surnames (case-insensitive) to exclude them
    member_surnames_lower = set()
    for name in member_names:
        surname = _extract_surname(name)
        if surname:
            member_surnames_lower.add(surname.lower())

    # Filter pool to surnames not already in the member list
    available = [
        s for s in DUTCH_SURNAMES if s.lower() not in member_surnames_lower
    ]
    random.shuffle(available)

    generated = []
    seen_surnames = set()

    for surname in available:
        if len(generated) >= count:
            break
        if surname.lower() in seen_surnames:
            continue

        first = random.choice(FIRST_NAMES)
        generated.append(f"{first} {surname}")
        seen_surnames.add(surname.lower())

    return generated


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_demo_names(count=8, member_names=None):
    """Generate demo candidate names.

    If member_names is provided and contains at least 4 entries, names are
    generated by mashing up surname components.  Otherwise the fixed fallback
    lists are returned.

    Args:
        count: Number of names to generate (only used in mash-up mode).
        member_names: Optional list of "First Last" strings from the member DB.

    Returns:
        List of name strings.
    """
    if member_names and len(member_names) >= 4:
        return _generate_names_from_pool(member_names, count=count)

    # Fallback: return the static lists (combined)
    fallback = FALLBACK_ELDER_CANDIDATES + FALLBACK_DEACON_CANDIDATES
    return fallback


def load_member_names_from_db(db_path):
    """Load member names from the app's SQLite database.

    Expects a `members` table with `first_name` and `last_name` columns.

    Args:
        db_path: Absolute path to the SQLite database file.

    Returns:
        List of "first last" name strings.
    """
    names = []
    try:
        conn = sqlite3.connect(db_path)
        try:
            cursor = conn.execute(
                "SELECT first_name, last_name FROM members"
            )
            for row in cursor:
                first, last = row
                if first and last:
                    names.append(f"{first.strip()} {last.strip()}")
        finally:
            conn.close()
    except (sqlite3.Error, OSError):
        pass
    return names


def load_member_names_from_external(data_dir):
    """Load member names from external sources in priority order.

    Checks, in order:
      1. data/members.db  — SQLite with members/attendees table, name/full_name column
      2. data/members.csv — CSV with name/full_name column
      3. config/members.txt — plain text, one name per line

    Args:
        data_dir: Base directory to search within.

    Returns:
        List of name strings, or empty list if nothing found.
    """
    # 1. SQLite database
    db_path = os.path.join(data_dir, "data", "members.db")
    if os.path.isfile(db_path):
        names = _load_from_sqlite(db_path)
        if names:
            return names

    # 2. CSV file
    csv_path = os.path.join(data_dir, "data", "members.csv")
    if os.path.isfile(csv_path):
        names = _load_from_csv(csv_path)
        if names:
            return names

    # 3. Plain text file
    txt_path = os.path.join(data_dir, "config", "members.txt")
    if os.path.isfile(txt_path):
        names = _load_from_txt(txt_path)
        if names:
            return names

    return []


# ---------------------------------------------------------------------------
# Internal loaders for external sources
# ---------------------------------------------------------------------------

def _load_from_sqlite(db_path):
    """Try to load names from a SQLite database at db_path."""
    names = []
    try:
        conn = sqlite3.connect(db_path)
        try:
            # Try members table first, then attendees
            for table in ("members", "attendees"):
                try:
                    # Try full_name column first, then name
                    for col in ("full_name", "name"):
                        try:
                            cursor = conn.execute(
                                f"SELECT {col} FROM {table}"  # noqa: S608
                            )
                            for row in cursor:
                                val = row[0]
                                if val and str(val).strip():
                                    names.append(str(val).strip())
                            if names:
                                return names
                        except sqlite3.OperationalError:
                            continue
                except sqlite3.OperationalError:
                    continue
        finally:
            conn.close()
    except (sqlite3.Error, OSError):
        pass
    return names


def _load_from_csv(csv_path):
    """Load names from a CSV file with a name or full_name column."""
    names = []
    try:
        with open(csv_path, newline="", encoding="utf-8-sig") as fh:
            reader = csv.DictReader(fh)
            if reader.fieldnames is None:
                return names
            # Determine which column to use
            col = None
            for candidate in ("full_name", "name"):
                if candidate in reader.fieldnames:
                    col = candidate
                    break
            if col is None:
                return names
            for row in reader:
                val = row.get(col, "").strip()
                if val:
                    names.append(val)
    except (OSError, csv.Error):
        pass
    return names


def _load_from_txt(txt_path):
    """Load names from a plain-text file, one name per line."""
    names = []
    try:
        with open(txt_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if line and not line.startswith("#"):
                    names.append(line)
    except OSError:
        pass
    return names
